### ISSUE TITLE
Docs: show how to use Repromise with let* syntax (OCaml-only)

### ISSUE THREAD

**Issue by aantron** [aantron/promise#42]

**Comment by simontegg** [comment]
Congrats on getting to 1.0
Related to this pre-1.0 it was pretty easy to get running with `bs-let`. Is this still posiible with the new API?

**Comment by aantron** [comment]
Thanks! I will post proper announcements soon.

It should be slightly easier with the new API. The core declaration is now

```reason
let let_ = Promise.flatMap;
```

I'll ping bs-let about this after the announcements, or you're welcome to send them a PR :)

**Comment by aantron** [comment]
I sent a [PR](https://github.com/reasonml-labs/bs-let/pull/7) to bs-let.

I'm going to close this issue, as I've focused the library on Reason/JS for now (the native stuff is still there, I'll develop it more later). Reason doesn't have `let*` yet (AFAIK), and I don't want to explictly recommend bs-let either, as it seems to also be a temporary solution until `let*`.
