### ISSUE TITLE
BuckleScript 8.0.0 breaks listToArray / Promise.all

### ISSUE THREAD

**Issue by cknitt** [aantron/promise#56]
The internal representation of lists changed in BuckleScript 8.0.0. Lists are now encoded as `{hd, tl}`, not as nested arrays anymore.

This breaks the functions `listToArray` and `arrayToList` and thereby all functions relying on them (`Promise.all`, `Promise.race`).

**Comment by bobzhang** [comment]
The listToArray and arrayToList seems to be interesting that we can absorb it in upstream

**Comment by jfrolich** [comment]
Why are these functions in this library? Isn't it better to use `Belt.List.toArray` and `Belt.List.fromArray`?

**Comment by aantron** [comment]
Yes, I will switch the library to the Belt functions and do a release. I don't immediately recall why I added these implementations.

**Comment by aantron** [comment]
The fixed version is now [in npm](https://www.npmjs.com/package/reason-promise) as [reason-promise@1.1.0](https://github.com/aantron/promise/releases/tag/1.1.0). Thanks @cknitt for the report!

**Comment by cknitt** [comment]
Thanks a lot @aantron! 🎉
