### ISSUE TITLE
Format with refmt?

### ISSUE THREAD

**Issue by cknitt** [aantron/promise#59]
Is there a reason why the source is not formatted with refmt?

**Comment by aantron** [comment]
Yes.

1. When I last tried refmt (admittedly, ~2 years ago), I found it made the code much less legible to me. Among other things, it butchers the consistency of the `.rei` file for the many repetitive functions, by formatting them only locally according to the lengths of the tokens in each function signature.
2. Outside contributors are so rare that I found using a global "blind" format not worth the tradeoff in light of (1).

See also #48.

**Comment by cknitt** [comment]
Ah, ok. Sorry, didn't see #48. Yes, refmt certainly comes with some trade-offs. Personally, I prefer not having to think about formatting anymore, even if the automatic formatting is less than perfect.
